version: '3'

volumes:
  postgres_data:

networks:
  local_area:
    driver: bridge

services:

  postgres:
    image: postgres:15.3-alpine
    container_name: repository
    restart: always
    networks:
      local_area:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 9920:${POSTGRES_PORT}

  flyway:
    image: flyway/flyway
    networks:
      local_area:
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      - postgres
    command: -url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} migrate

  task:
    container_name: task-cont
    build:
      context: ../
      dockerfile: cmd/Dockerfile
    networks:
      local_area:
    restart: unless-stopped
    env_file:
    - .env
    ports:
    - ${SERVER_PORT}:${SERVER_PORT}

